"""Growth vNext 학습 세션 도메인 상수.

reading/session.py 의 viewer 본인확인(verified)과 이름이 비슷해도 의미가 다르다.
이 모듈의 record_verification=verified 는 교사가 실제 교재를 확인한 학습 기록이다.
"""
from feature_models import (
    ACTOR_CHILD,
    ACTOR_TEACHER,
    NON_STUDY_SOURCE_CENTER,
    NON_STUDY_SOURCE_SYSTEM_HOLIDAY,
    RECORD_VERIFICATION_OBSERVED,
    RECORD_VERIFICATION_VERIFIED,
    STUDY_CHANGE_CREATED,
    STUDY_CHANGE_DELETED,
    STUDY_CHANGE_UPDATED,
    STUDY_STATUS_EXPLICIT_NOT_STUDIED,
    STUDY_STATUS_STUDIED,
    STUDY_STATUS_UNKNOWN,
)

STUDY_STATUSES = (
    STUDY_STATUS_STUDIED,
    STUDY_STATUS_EXPLICIT_NOT_STUDIED,
    STUDY_STATUS_UNKNOWN,
)
RECORD_VERIFICATIONS = (
    RECORD_VERIFICATION_OBSERVED,
    RECORD_VERIFICATION_VERIFIED,
)
NON_RANGE_STUDY_STATUSES = (
    STUDY_STATUS_EXPLICIT_NOT_STUDIED,
    STUDY_STATUS_UNKNOWN,
)

MIN_PAGE = 1
MAX_PAGE = 2000
TITLE_MAX = 120

INPUT_CHANNEL_TEACHER = 'teacher'
INPUT_CHANNEL_CHILD = 'child'
